version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - IMAGE_URI=$ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO_NAME
      - IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION:-$(date +%Y%m%d%H%M%S)}
      - IMAGE_TAG=$(echo $IMAGE_TAG | cut -c 1-8)
  build:
    commands:
      - echo Build started on `date`
      - docker build -t $IMAGE_URI:$IMAGE_TAG .
      - docker tag $IMAGE_URI:$IMAGE_TAG $IMAGE_URI:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $IMAGE_URI:$IMAGE_TAG
      - docker push $IMAGE_URI:latest
      - echo Registering new Task Definition...
      - sed -e "s|{ACCOUNT_ID}|$ACCOUNT_ID|g" task-definition.json > task-def-resolved.json
      - sed -i "s|$ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/ci-cd-demo-app:latest|$IMAGE_URI:$IMAGE_TAG|g" task-def-resolved.json
      - NEW_TASK_DEF=$(aws ecs register-task-definition --cli-input-json file://task-def-resolved.json --region $AWS_DEFAULT_REGION --query 'taskDefinition.taskDefinitionArn' --output text)
      - echo "New Task Definition:$NEW_TASK_DEF"
      - echo Updating ECS service...
      - aws ecs update-service --cluster ci-cd-demo-cluster --service ci-cd-demo-service --task-definition $NEW_TASK_DEF --region $AWS_DEFAULT_REGION
      - echo "ECS deployment triggered. Blue/Green proceeds in background."
